<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Start.aspx.cs" Inherits="FileSaver.UI.Views.FiletoDBSaver.Start" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <link rel="stylesheet" type="text/css" href="../../css/bootstrap.css" />
    <script type='text/javascript' src="../../scripts/bootstrap.js"></script>
    <script type="text/javascript" src="../../scripts/common.js"></script>
    <title></title>
</head>
<body style="background: #f0f8ff url(../../css/theme/Images/main-bg.gif);">
    <form id="form1" runat="server">
        <div class="d-flex align-items-center justify-content-center" style="margin-top: 50px;">
            <table>
                <tr>
                    <td>
                        <b>Select a file to upload:</b>
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:FileUpload ID="fileUploadPerson" runat="server" />
                        <asp:Button ID="uploadButton" Text="Upload file" runat="server"
                            OnClick="uploadButton_Click" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="uploadStatusLabel" runat="server" class="font-weight-bold"/>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <asp:GridView ID="gridPersonData"
                            runat="server"
                            CssClass="table table-responsive table-striped table-hover"
                            AutoGenerateColumns="False"
                            ShowHeader="True"
                            DataKeyNames="Identity"
                            AutoGenerateDeleteButton="True"
                            AutoGenerateEditButton="True"
                            OnRowEditing="gridPerson_RowEditing"
                            OnRowCancelingEdit="gridPerson_RowCancelingEdit"
                            OnRowUpdating="gridPerson_RowUpdating"
                            OnRowDeleting="gridPerson_RowDeleting">
                            <HeaderStyle CssClass="DataGridNonFixedHeader" BackColor="#4096EE" Font-Bold="True" ForeColor="White" />
                            <Columns>
                                <asp:BoundField DataField="FirstName" HeaderText="First Name" />
                                <asp:BoundField DataField="Surname" HeaderText="Surname" />
                                <asp:BoundField DataField="Age" HeaderText="Age" />
                                <asp:BoundField DataField="Sex" HeaderText="Sex" />
                                <asp:BoundField DataField="Mobile" HeaderText="Mobile Phone" />
                                <asp:BoundField DataField="Active" HeaderText="Active" />
                            </Columns>
                        </asp:GridView>
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Panel runat="server" Visible="false" ID="saveStatusPanel">
                            <asp:Label ID="saveStatusLabel" runat="server" class="float-left font-weight-bold"/>
                        </asp:Panel>
                    </td>
                    <td>
                        <asp:Panel runat="server" Visible="false" ID="saveButtonPanel">
                            <asp:Button ID="saveButton"
                                Text="Save" runat="server"
                                OnClick="saveButton_Click"
                                OnClientClick="validatePersonData(<%# gridPerson.ClientID %>);"
                                class="float-right" />
                        </asp:Panel>
                    </td>
                </tr>
            </table>
        </div>
    </form>
</body>
</html>
